### ISSUE TITLE
Support Phoenix Channel Authentication

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/coherence#118]
Evaluate how Coherence could support Phoenix channel authentication and implement something if there is value here.

**Comment by RobertFr0st** [comment]
This sounds like an interesting feature I may be able to help on.  Judging by the likes this feature is getting, there is definitely value to be added.  A common use case I've dealt with is this:
  Personal Channels - Since channels are often used like an API's to speak with front end frameworks it would be nice if a logged in user (client) could get their model info from the server.

Since Phoenix supports forcing incoming connections to TLS, from a security standpoint, it should be as simple as authenticating the user.  According to Phoenix's channel documentation they advise using tokens, which there is an example of here: "https://hexdocs.pm/phoenix/Phoenix.Token.html".  This should be a pretty simple expansion on the current authentication system as the user is already logged in, so the token should be already available for the user to grab.  However, rather than tack it onto the connection it would be added to the socket.  I'm not too familiar with the channel routes in user_sockets, so a question I have is, is there a way to tie this authentication using a plug?  If so then channel authentication from an end user perspective would be very stylistically similar to the current implementation for web routes.  Any thoughts, ideas?
