### ISSUE TITLE
Current password should not be prompted when creating new recoverable password.

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/coherence#123]
When recovering your password, the current password field should not be presented since the reason your creating a new password is presumably because you forgot your old one.

**Comment by fabrik42** [comment]
Hi!
I am facing the same problem (working with the current master version of the lib). Please let me know if I can be of any help. :)

Best,
Christian

**Comment by kimquy** [comment]
@fabrik42 I have worked on that bug before. I have removed it from the view if you look at this PR https://github.com/smpallen99/coherence/pull/124/files, however I have missed some other places ?

**Comment by fabrik42** [comment]
Hey @kimquy, thanks for your fast reply!

I don't think it is related to the view, but to the validations?

Here is an excerpt from my log, inspecting the changeset in `MyApp.Coherence.PasswordController.update/2`

```
[info] POST /passwords/1
[debug] Processing by MyApp.Coherence.PasswordController.update/2
  Parameters: %{"_csrf_token" => "xxx, "_method" => "put", "_utf8" => "✓", "id" => "9", "password" => "[FILTERED]"}
  Pipelines: [:browser]

#Ecto.Changeset<action: :update,
 changes: %{password: "111111", password_confirmation: "111111",
   reset_password_sent_at: nil, reset_password_token: nil},
 errors: [current_password: {"can't be blank", []}], data: #GbKit.User<>,
 valid?: false>
```

As you can see, the update fails, because the current password is not allowed to be blank.

I think the problem is here: https://github.com/smpallen99/coherence/blob/59ab00b1cc535cdc07676c0fd7989e527f935d54/lib/coherence/schema.ex#L244-L247

`validate_coherence/2` always checks for the current password, if the setting is set, even when resetting the password.

What do you think?

Best,
Chistian

**Comment by kimquy** [comment]
Hi Christian,

I do aware of this problem before. When I implemented it, I did check for the part that it should not require password when we want to reset the password.

However we do want to require password when user try to do the update on other information. I think in this case you're trying to do the update right ?

**Comment by kimquy** [comment]
If you don't want this behavior, maybe you can turn this config off ?

```elixir
config :coherence,
  require_current_password: false
```

**Comment by fabrik42** [comment]
Hi!
Yes, turning off this setting works. But I want the user to enter a password in order to change the registration information. I think this makes sense as a feature, when the user is logged in, so an attacker can't change the password, if the user forgets to lock out.

But it makes no sense in the use case of the password reset field.

**Comment by fabrik42** [comment]
I think the `require_current_password` must be applied in `Coherence.RegistrationController.update/2` but must not be applied in `Coherence.PasswordController.update/2`.

I could fix this in my project with a custom `changeset(model, params, :password)` function in the user model, but I thought this is a general issue?

**Comment by kimquy** [comment]
Yeah, I think it makes sense. Can you create a PR for this? That's gonna be very helpful. Think quite many people facing this issue.

**Comment by fabrik42** [comment]
Sure, I can give it a try!

**Comment by gitten** [comment]
There is an `if` statement in the create function that uses `checkpw()`. It seems like this might always evaluate to nil if the password field is left blank. Isn't the convention to do this with a changeset?
[web/controllers/unlock_controller.ex](https://github.com/smpallen99/coherence/blob/e292645336da2ac9a4d9b43aaadfb56b7d66653d/web/controllers/unlock_controller.ex#L49)

**Comment by fabrik42** [comment]
Hi @gitten! I am not sure how this correlates with the password reset issue. Could you elaborate a little bit?

**Comment by smpallen99** [comment]
This is working on master
