### ISSUE TITLE
MyApp.Coherence.RegistrationController.init/1 is undefined 

### ISSUE THREAD

**Issue by gpcweb** [smpallen99/coherence#155]
I guess this is because there is no RegistrationController under my controller's directory, but didin't this task `mix coherence.install --full-confirmable` should copy or generate this file on my app??

I'm really new on elixir/phoenix and my english is not very good so I apologize in advance.

**Comment by egeersoz** [comment]
Controllers are not generated by default. If you want to install them, you need to pass the `--controllers` flag when running `mix coherence.install`.

Alternatively, you can use the built-in controllers (under `deps/coherence/web/controllers`). The challenge with that approach is that you can't customize them.

**Comment by gpcweb** [comment]
But that behavior its not what you will expect from  a full installation task, besides the task copy views and email functions as well to my project.

**Comment by smpallen99** [comment]
I didn't include the controllers by default since I did not believe they were something that people would want to modify often. After using Coherence for a while myself, I still find myself not requiring generated controllers. 

So, I'm included to leave this behaviour unless I get a lot of feedback from the community otherwise. Perhaps this could use better docs to set the correct expectation. PR welcome 👍

**Comment by egeersoz** [comment]
Here's one very recent example...

I want to send a welcome email to the user after they confirm their account.

With the default installation behavior, the only way to do this is to use `Coherence.Redirects` and piggyback on the `confirmation_edit/2` function that it makes available.

Except it's not possible to make it work, because the `params` map that the Confirmation Controller passes to `confirmation_edit/2` contains only the confirmation token, which can no longer be used to look up the user (to be able to send them an email) because the Confirmation Controller has already set the user's `confirmation_token` field to `nil`.

That's why I had to force the installer to generate controllers so that I could customize the behavior. I ended up inserting the user's email address into the params object before they are redirected to `:confirmation_edit`:

```
case Config.repo.update(changeset) do
  {:ok, _user} ->
    params = Map.put(params, "email", user.email) # insert the user email into params
    conn
    |> put_flash(:info, "User account confirmed successfully!")
    |> redirect_to(:confirmation_edit, params)
```

Redirects.ex:
```
def confirmation_edit(conn, params) do
  MyApp.Email.welcome_html(params["email"])
  |> MyApp.Mailer.deliver_later
end
```
