### ISSUE TITLE
Issues with reset password

### ISSUE THREAD

**Issue by tslocke** [smpallen99/coherence#159]
First issue - I'm getting a password can't be blank error when submitting the reset password form.

I commented out `validate_coherence(params)` in the user model as a temporary experiment, and the form then submits without error. I see the email text and reset link in the console output.

Second issue is I get "Invalid reset token" if I visit the URL from the email. Am investigating that one.

**Comment by tslocke** [comment]
OK the second issue is that I hadn't added `++ coherence_fields` to `cast` in my `User.changeset` so the reset token was not being saved in the DB.

For the first issue, I have my `User.changeset` call `validate_coherence` conditionally:

    if Map.has_key? params, "password" do
      changeset |> validate_coherence(params)
    else
      changeset
    end

Is seems wrong that I have to do that, but it's working at least.

**Comment by fabrik42** [comment]
Hi! I am facing the same problem. It has to do with the `require_current_password` configuration.
It is set to true by default, but it seems this gets also applied to the password reset form. This makes no sense, because you wouldn't be there, if you knew your password, so I guess it's a bug. :)

There is already issue #123 regarding this problem.

**Comment by kimquy** [comment]
Hi @tslocke 

Maybe you can update your config like

```elixir
config :coherence,
  require_current_password: false
```

so coherence will not ask you for the current password.

**Comment by tslocke** [comment]
Since I opened this and it looks like it's a dup of #123, I'll close it. Thanks for your responses :)
