### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by egeersoz** [smpallen99/coherence#167]
No commits in three weeks is a bit worrisome. If the project is not under active development, perhaps @smpallen99 can outline future goals so others can start contributing. I for one would be willing to help, as I'm sure so would others.

**Comment by smpallen99** [comment]
I’ll be spending some time tomorrow on open source. get back to you then. sorry for going dark.

**Comment by smpallen99** [comment]
@egeersoz The goal right now is to work through the backlog of issues. I'm working on a project right now where I'm going to need channel auth. So I suspect I'll be adding that very soon.

**Comment by niccolox** [comment]
I'd be interested in chipping in also

my main interest right now is the constellation Coherence + Ueberauth + Guardian + Exadmin (maybe Shield)
https://github.com/smpallen99/coherence/issues/38#issuecomment-284270702

**Comment by hakunin** [comment]
This project is super important for Phoenix newbs like me, since signing users up is the first thing any project needs. Being able to knock this off in a couple hours with `coherence` moved my weekend project much further and improves the learning curve since I didn't have to learn everything this thing does and do it myself.

**Comment by smpallen99** [comment]
@hakunin Thanks for the great feedback!!
