### ISSUE TITLE
Support for a multilanguage

### ISSUE THREAD

**Issue by stenionobres** [smpallen99/coherence#168]
Hello.

I have a doubt about a coherence. How to change the language of messages? In resume, works with globalization. Is it possible make some configuration in a mix.exs?

**Comment by agustif** [comment]
GetText?

**Comment by tmbb** [comment]
The obvious way would be to add the relevant `dgettext` calls with a domain named `"coherence"`. @smpallen99 do you agree with this approach? Also, could we distribute already translated **.po** files? Maybe we could add them to the coherence templates.

**Comment by smpallen99** [comment]
I did some work on adding gettext a while back. I pushed the  [gettext](https://github.com/smpallen99/coherence/tree/gettext) branch. 

I did not use dgettext, but I should have. Also, some tests are not passing on the branch so that needs to be fixed. I would also like a review of my changes. I have not used gettext that much so there may be room from improvements. 

I'm looking for someone to pick this up and complete it. Should be pretty easy to change the gettext calls to dgettext("coherence" with global search and replace.

Yes, I would agree it would be nice to include translation .po files. Just need some volunteers 👍 

@tmbb are you volunteering to complete the work? 🥇

**Comment by smpallen99** [comment]
Oh ya, this branch is behind master a bit...

**Comment by tmbb** [comment]
While awaiting your answer I went ahead, cloned the current master and added the `dgettext("coherence", ...)` calls (all of them, I think). How do you want me to submit a pull request? Should I create `gettext` branch, add those changes and ubmit?

**Comment by smpallen99** [comment]
Can you do a quick compare with my gettext branch? if your happy with yours, go ahead a submit a PR against master. I'll merge your PR after I review it.

**Comment by smpallen99** [comment]
oh ya, and thanks @tmbb :)

**Comment by tmbb** [comment]
Your branch is very similar to mine. You used `gettext` instead of `dgettext` and in some email templates I used variable interpolation instead of what you did (you were using elixir's templates as a way of doing variable interpolation, which only works for languages in which the word order is the same as English).

Apart from that it's the same.

**Comment by agustif** [comment]
I could do Spanish and Catalan

**Comment by tmbb** [comment]
PR done.

**Comment by tmbb** [comment]
I could do Portuguese (pt_PT).

**Comment by smpallen99** [comment]
Thanks to @tmbb, we now have gettext implemented. I'm going to open another issue to look for translations
