### ISSUE TITLE
Sessions and restarts

### ISSUE THREAD

**Issue by noma4i** [smpallen99/coherence#22]
Looks like Coherence doesn't remember users between vm/app restarts. Every deploy all users are kicked.

With option `Remember me` users will remain logged in. For now Iv put that checkbox as hidden field so every user is remembered.

As and addition I can see DB been hit on every request when `Remember me` used. I think it's not efficient to poll database for sessions if session exists in-memory.

**Comment by smpallen99** [comment]
This should have been fixed in v0.1.3. What version are you running? Do you have the :rememberable option in your config/config.exs file?

The rememberable implementation updates the {user, series, hash} tuple on each request. This is a security measure to restrict access for someone how might have obtained the login cooke from someone else. 

If you just want sessions surviving an application reload, then you can enable a database backend for storing the session key. This will ensure sessions survive a rootboot, but will not save the session if a user closes their browser.

**Comment by noma4i** [comment]
: rememberable cause sync db hit on every request slowing down whole application

**Comment by smpallen99** [comment]
@noma4i I'm not sure how to do a secure remember me without database access on each request. Are you looking for an insure version of the feature that does not validate series/token pairs on each request.

Another option could be to backend the the first request in the db and in memory store. Each subsequent request generates new series/token pair from memory. In the case of server restart, an old token fetched from the database and stored in memory. I believe this would give the hijack protection unless the server restarts.

What do you think?

**Comment by noma4i** [comment]
InMemory storage looks fine as it eliminates constant db polling especially db update request which is sync for now and is pretty expensive.  That will help to escape situation with users been kicked.

**Comment by smpallen99** [comment]
I've opened issue #29 to capture the feature request. Closing this issue.
