### ISSUE TITLE
Support phoenix 1.3 release

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/coherence#242]
The newly released phoenix 1.3 has significant changes that affect coherence. Need to refactor to support projects created with `mix phx.new`

**Comment by tmbb** [comment]
I can help with context integration (finish and polish my mix task), but I'd like you to have a look at my new pull request, because it affects what I can put in the context generators.

With the new pull request we can update all logins (sessions) belonging to a given user, and if so, that should be integrated with the context generators. Without the functionality in the new pull request, we are more limited: we can only upgrade the *current* user login (not all logins).
