### ISSUE TITLE
The wrong module is used for UserEmail and Maile when sending user emails.

### ISSUE THREAD

**Issue by jbosse** [smpallen99/coherence#252]
I think this may only manifest itself in umbrella installs, but when performing an action that generates an email (such as forgot password) the expected function MyProject.Coherence.UserEmail does not exist because it was generated in the web module (MyProject.Coherence.UserEmail does exist).

**Comment by jbosse** [comment]
I didn't realize I included this in the PR. 😬

**Comment by cdesch** [comment]
@jbosse Is this something needs to be configured differently in the Web portion of the umbrella app?

Should the email be configured in `MyProject.Coherence.UserEmail` or `MyProjectWeb.Coherence.UserEmail` 

In my umbrella app, the controllers with Coherence are in the `MyProjectWeb`, although the models and data access is in the `MyProject`. Is there a call back i'm missing to get email to send?

**Comment by cdesch** [comment]
I was able to fix it. 

I had to override the `/lib/coherence/config.ex` file (`Coherence.Config`) and update the function `mailer?` with:

 ```
def mailer? do
    !!Application.get_env(:coherence, MyProjectWeb.Coherence.Mailer)
  end
```

I think this is a version `4.x` bug as it was default set to `!!Application.get_env(:coherence, CoherenceDemo.Coherence.Mailer)`, which works if you name your mailer to that in your `config/config.exs`. This looks like it is fixed in `5.x`.
