### ISSUE TITLE
Registration edit, update, delete actions

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#27]
I've seen Coherence generates routes for those actions but they aren't defined by the controller.

I guess this is waiting for implementation?

**Comment by smpallen99** [comment]
Your correct, they are not used. I'm not sure yet if I should provide provide an implementation for them or just remove the routes. What do you think?

**Comment by jaimeiniesta** [comment]
It would be great if they could be implemented, both for account edit (email/password change), and for account cancellation.

**Comment by agustif** [comment]
For account cancellation, what would be the best way to do it? 
[1] ask for your current password for confirmation before account cancellation.
  The Good: It looks safer since some forgot logged in session in a public computer poses no real threat (nobody can delete your account, if they don't know the password)
  The Bad:  I find it irritating myself when I want to delete an old account which I'm getting notifications via email from, and I follow they 'unsubscribe link', can manage some stuff in my panel, but if I want to delete my account I need to remember my password. Which usually ends up using a recover password function (Which isn't implemented here on coherence yet, but its an already open issue)


[2] send a confirmation link to the account.email which needs to be clicked before account is queued for cancellation.
  The Good: No password needed, so any valid session could request this, and the backend should send an email to ask for confirmation. Email hacking is a long fetch, possible (Maybe a 24-48h delay and posterior notification with possible undo of cancel action would be required for some projects where account stealing is a thing)
  The Bad: Some times people change emails, but that shouldn't be the web app responsability 

Any way, sorry for the rambling just wanted to add my 2 cents since I hope to use coherence in my phoenix side project.

**Comment by smpallen99** [comment]
+1 on [1] above. 

@agustif Why did you say password recovery is not not supported. The recoverable feature should be fully supported.

**Comment by agustif** [comment]
Sorry @smpallen99 I tried the library but maybe I didn't use the --recoverable flag during install 

I was just playing around with coherence demo and saw the recoverable feature implemented, so never mind and let me edit my previous comment

**Comment by jaimeiniesta** [comment]
+1 to [1] as well, it's a bit of extra work for the user but it's worth for the security.
