### ISSUE TITLE
How to authenticate in a controller test?

### ISSUE THREAD

**Issue by jesseshieh** [smpallen99/coherence#290]
Hi, apologies if this is covered somewhere, but I did some searching and couldn't find the answer. I'm writing a phoenix controller test for an endpoint that requires authentication using Coherence and I'm unsure how to do it. Are there instructions somewhere about this?

The pipeline I'm using looks like this
```
  pipeline :protected do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, db_model: Web.User, protected: true
  end
```

I think my controller test needs to do something like csrf tokens and cookies and perhaps not just `assign(conn, :current_user, user)`

Thanks for the help!

**Comment by das3in** [comment]
There's a wiki article about testing protected routes here https://github.com/smpallen99/coherence/wiki/Testing-with-Coherence - basically the idea is to create and pass in `current_user`

This could use some more documentation though. For example I'm getting 302's on the non-GET actions and I'm trying to figure out why.

**Comment by jesseshieh** [comment]
Thanks!

**Comment by zwippie** [comment]
@das3in I'm experiencing the same 302's with redirects to `/sessions/new` on non-GET actions in my tests. Did you find a solution?

**Comment by zwippie** [comment]
Update: Creating a new session before each test instead of just setting the current user seems to do the trick:

```
setup %{conn: conn} do
    user =
      User.changeset(%User{}, @user_attrs)
      |> Medox.Repo.insert!
    conn = post(conn, session_path(conn, :create), %{session: @user_attrs})
    {:ok, conn: conn, user: user}
  end
```

This could be made more modular:

```
  setup [:create_user, :login_as_registered_user]

  # ...tests...

  defp create_user(_) do
    user =
      User.changeset(%User{}, @user_attrs)
      |> Medox.Repo.insert!
    {:ok, user: user}
  end

  defp login_as_registered_user(%{conn: conn}) do
    conn = post(conn, session_path(conn, :create), %{session: @user_attrs})
    {:ok, conn: conn}
  end

**Comment by International** [comment]
@zwippie I've also encountered this. Your fix works, did you ever figure out why those redirects happen in the first place?

For me it happens in a test case:
```
    test "deletes chosen project", %{conn: conn, project: project} do
      conn = delete conn, project_path(conn, :delete, project)
      assert redirected_to(conn) == project_path(conn, :index)

      assert_error_sent 404, fn ->
        get conn, project_path(conn, :show, project)
      end
    end
```

basically the get inside the `assert_error_sent` is failing because this receives a 302 .

**Comment by International** [comment]
@das3in @zwippie  After investigating a bit, I don't think it's an issue with the library. From what I read and tried, I think the cause is the connection recycling, mentioned [here](https://hexdocs.pm/phoenix/Phoenix.ConnTest.html#module-recycling). I've also found a pretty relevant [SO question](https://stackoverflow.com/questions/46363292/losing-conn-assigns-in-the-middle-of-a-test) . Changing the body of my test to:
```
    test "deletes chosen project", %{conn: conn, project: project} do
      conn = delete conn, project_path(conn, :delete, project)
      assert redirected_to(conn) == project_path(conn, :index)
      saved_assigns = conn.assigns

      assert_error_sent 404, fn ->
        conn = conn
          |> recycle()
          |> Map.put(:assigns, saved_assigns)

        get conn, project_path(conn, :show, project)
      end
    end
```
fixed the issue for me.

**Comment by zwippie** [comment]
@International That's sort of what I'm seeing here.

I have tried to grasp the differences between a `conn` when logging in through the `sessions` endpoint (real login) and a `conn` when just assigning the `current_user` (fake login), but found it hard to analyze and debug exactly what is going on.

You mention in your edit that the `conn.assigns.current_user` is no longer present, but that would be **after** the get request, not before.

What I'm seeing here is that, with a fake login, any _first_ request (get/post/patch/delete) is handled properly, it also returns the updated conn with the `current_user` still assigned. But the _next_ request that receives that updated conn seems to ignore the `current_user`. Therefore, the request is halted, probably by the [require_login plug](https://github.com/smpallen99/coherence/blob/956b6b7412951f452386cc5861d5cc5c7896be04/lib/coherence/plugs/require_login.ex) and redirected to the login page. But although there is no more `current_user` in the connection returned by the second request, the rest of the data is stil there, including flash messages and the like!

With a real login, all requests are seen as authenticated and handled properly.

That is as far as I'm getting right now. [This Phoenix.ConnTest part about recycling](https://hexdocs.pm/phoenix/Phoenix.ConnTest.html#module-recycling) also looks interesting, just like  [this StackOverflow answer](https://stackoverflow.com/a/39707535/409792), which simply implies that all assigns are gone after a redirect, that would make sense too. Perhaps this whole issue is as **simple** as that.

But then why are the assigns not restored after a redirect, as is happening with a real login? What does it take to trick coherence into a better, persisted fake login?  I'm still looking for a solution because all my controller tests with protected routes are getting dead slow now with a post to the login page before every example.

**Comment by julianespinel** [comment]
In addition to what @zwippie said, please make sure the user you created was already confirmed (verified).

If you try to create a session (login) with a user who hasn't confirmed his/her email, you will get HTTP status code `406` as a response. Why? Because you can't login with a user that has not confirmed his/her email.

To create confirmed (verified) a user you need to add the key `confirmed_at` to the `@user_attrs`.

Example:
```
  @user_attrs %{
    name: "test",
    email: "test@example.com",
    password: "pwdtest",
    password_confirmation: "pwdtest",
    confirmation_sent_at: DateTime.utc_now,
    confirmed_at: DateTime.utc_now() # Create a verified/confirmed user
  }
```
