### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#31]
It would be great to be able to internationalize the flash messages and validation errors, both for preparing the app for other languages, and to customize the messages even if you leave them in English.

**Comment by agustif** [comment]
I've seen GETTEXT widely used on phoenix stuff, maybe it makes sense here too.

**Comment by smpallen99** [comment]
Yep. I just had someone do this for ex_admin using gettext. I really find it verbose with all the gettext calls so I think I’ll create a sigil for it.

**Comment by smpallen99** [comment]
This would make a great contribution from the community. PR welcome :)

**Comment by agustif** [comment]
Im somewhat junior but if you are up to the task of guiding the effort I can put hours and thought into it!

Let me know what you think! Im Spanish-Native so that could probably help to translating to something else than english for testing the i18n branch

**Comment by smpallen99** [comment]
@agustif Yes, I'm up for the task of giving you some guidance. There should be a some good guides out there for getting started with GETTEXT. You can also look at my [ExAdmin](https://github.com/smpallen99/ex_admin) since someone already added i18n to it using GETTEXT.

I when your ready to start converting all the messages, I suggest you write a custom sigil `~g()`. This way, the code will be filled with `~g"Some internationalized text"` instead of the more verbose `gettext("Some Internationalized text")`. Something I did not like about the ExAdmin implementation.

You can review [Elixir Sigils](http://elixir-lang.org/getting-started/sigils.html) if your not familiar with creating a custom sigil. Its pretty simple.

When your ready to send a pull request, I would appreciate if you generate one against a branch and not into master on my repo. This way, I can merge into the branch and do some testing before merging into master. 

Let me know what else I can help with. If you want to have an interactive discussion, you can find on Slack `@smpallen99`.

Steve

**Comment by agustif** [comment]
Hi @smpallen99 I've been toying around with this, let me know if Im on a good path.

1. Add gettext to mix.exs
2. mix deps.get
3. Added sigil_g module to web/gettext.ex

Testing it
```elixir
  def sigil_g(string, []), do: IO.puts("gettext #{string}")

#Example
iex(1)> import Coherence.Gettext
Coherence.Gettext
iex(2)> ~g/elixir school/
gettext elixir school
:ok
iex(3)>

```
Should I continue copying dirs/files from priv/gettext ExAdmin project? 

Thanks for the help.

I could also go on and try to implement this on ExAdmin and replace some of the actual GetText with the sigil_g, lemme know if its a PR you might be interested in.

**Comment by smpallen99** [comment]
Looks like this is not going to be as easy as I thought it would be. Your sigil about is not quite correct since it is only printing `gettext string`. However, it you change the sigil to `do: gettext(string)` we get a compile error warning us not to call gettext with a variable. There is a way around this, but apparently it will not allow the gettext generate some of its files. 

I guess we are stuck with the clumsy `gettext` interface.

**Comment by agustif** [comment]
Yeah, I was stuck on the compile error using gettext directly. So translating using gettext ExAdmin way is what I should follow on?

**Comment by smpallen99** [comment]
Yes

**Comment by bitboxer** [comment]
I am just trying out coherence, but there are lots of places that need gettext, starting from the `coherence_view_helpers` to the flash messages. What is the status of this?

**Comment by smpallen99** [comment]
@agustif Have not heard from you for a file. Have you given up on this feature?

**Comment by bitboxer** [comment]
Since I will need this I can implement it. But I am a total elixir beginner :wink: . After looking through the files I have one question: there are some template files, e.g. `web/templates/email/confirmation.html.eex` that are the same as in the `priv/templates/coherence.install/`, but they are not copied to the `priv` folder when starting the `make_controller_templates.exs` task. Is there a reason for it? (Btw: is there a reason why this is not a mix task?)

**Comment by smpallen99** [comment]
I'll have to look at why I have templates under web/templates. They my be for test by I can't remember. 

make_controller_templates.exs was a quick solution when I found out that it was not easy to do from the mix install task. I didn't think of making is a mix task, which I think would be a good idea.

I would be grateful for an i18n contribution.

Steve

**Comment by bitboxer** [comment]
Okay, will ignore the files in the `web/templates` folder when translating. I will also add a gettext domain called "coherence" to separate the i18n texts from the application files.

**Comment by bitboxer** [comment]
Sorry for the delay in this ticket. I waited for the credo stuff, but now I am back at it and working on it. Already translated one of the controllers and gettext files are copied with the mix task. Next stop: i18n all the files 💪

**Comment by bitboxer** [comment]
The only problem I ran into so far: Coherence has its own Gettext and if you set the locale, you have to set the locale for the `Coherence.Gettext`, too. If anyone here has a smart Idea how to synch the app gettext and the coherence one, I am listening :wink:

**Comment by bitboxer** [comment]
Started a discussion about it [here](https://elixirforum.com/t/gettext-in-a-hex-package/3447).

**Comment by bitboxer** [comment]
There is now a ticket [here](https://github.com/elixir-lang/gettext/issues/147) That needs to be implemented. Till then something like this:

```
defmodule MyApp.Translations do
  def put_locale(locale) when is_binary(locale) do
    Enum.each([Coherence.Gettext, MyApp.Gettext], &Gettext.put_locale(&1, locale))
  end
end
```
(by @whatyouhide)

is needed in the main application using Coherence and it needs to call this method when it wants to set the current locale. Additionally in the `config.exs` I need to add something that sets the default locale in Coherence to be the same as the one from the target app.

Would it be okay for you all if I implement the above mentioned code and replace it when the feature in elixir is implemented?

**Comment by bitboxer** [comment]
@smpallen99 any opinion on how I should proceed?
