### ISSUE TITLE
Compilation error in file lib/MYAPP_web/coherence_messages.ex

### ISSUE THREAD

**Issue by jung-hunsoo** [smpallen99/coherence#329]
I'm retrying to use coherence on my phoenix 1.3 webapp.

When I run `mix ecto.reset` to renew migrations in dev env, a compilation error was occurred like this.

```elixir
== Compilation error in file lib/nohogu_web/coherence_messages.ex ==
** (ArgumentError) *gettext macros expect translation keys (msgid and msgid_plural) and domains to expand to strings at compile-time, but the given msgid doesn't.

Dynamic translations should be avoided as they limit gettext's ability to extract translations from your source code. If you are sure you need dynamic lookup, you can use the functions in the Gettext module:

    string = "hello world"
    Gettext.gettext(NohoguWeb.Gettext, string)

    (gettext) lib/gettext/compiler.ex:213: Gettext.Compiler.expand_to_binary/4
    expanding macro: NohoguWeb.Gettext.dgettext_noop/2
    lib/nohogu_web/coherence_messages.ex:75: NohoguWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    expanding macro: NohoguWeb.Gettext.dgettext/2
    lib/nohogu_web/coherence_messages.ex:75: NohoguWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers
```

Actually this error is simply resolved by merging line-divided messages in `coherence_messages.ex:75`.

If this is proved as a bug and the solution I'm using is appropriate, then I'll make PR.

**Comment by krystofbe** [comment]
This is definitely a bug

**Comment by fdietz** [comment]
Just ran into the same issue. In my case it was caused by an update of gettext library from 0.13.1 to 0.15.0.

**Comment by loongmxbt** [comment]
Same issue, delete the <> works fine.

**Comment by jung-hunsoo** [comment]
There's a bit confusing point.

After I looked through the [coh.install messages template file](https://github.com/smpallen99/coherence/blob/master/priv/templates/coh.install/coherence_messages.ex#L75), no chevrons were found.

I can only presume that the chevrons were added on coh.install process.

**Comment by cdesch** [comment]
The issue is fixed in the master branch [coherence_messages.ex](https://github.com/smpallen99/coherence/blob/master/priv/templates/coh.install/coherence_messages.ex), in commit [99d6250342531dd404f7bcc5407be533ab3fea5e](https://github.com/smpallen99/coherence/commit/99d6250342531dd404f7bcc5407be533ab3fea5e) but not in the `v0.5.0` version of [coherence_messages.ex](https://github.com/smpallen99/coherence/blob/v0.5.0/priv/templates/coh.install/coherence_messages.ex)

Removing the chevrons from this line in `coherence_messages.ex` does fix it:

    def you_are_using_an_invalid_security_token, do: dgettext(@domain, "You are using an invalid security token for this site! This security\n" <> 
    "violation has been logged.\n")

I made the fix in my own [fork](https://github.com/kickinespresso/coherence) on a [new v0.5.1 branch](https://github.com/kickinespresso/coherence/tree/v0.5.1)

    {:coherence, git: "https://github.com/kickinespresso/coherence", branch: "v0.5.1"}

I'm not sure how to go about properly making that kind of pull request to the rest of the project. If @smpallen99 thinks it is worth it and someone can give me some guidance on merging a fork into a `v0.5.1`, I'll give it a shot.

**Comment by scorsi** [comment]
Yeah, removing the "<>" fixed this.
Instead of:
```elixir
def you_are_using_an_invalid_security_token,
    do: dgettext(@domain, "You are using an invalid security token for this site! This security\n" <>
      "violation has been logged.\n")
```
Do:
```elixir
def you_are_using_an_invalid_security_token,
    do: dgettext(@domain, "You are using an invalid security token for this site! This security violation has been logged.\n")
```

**Comment by jung-hunsoo** [comment]
As @cdesch commented above, this bug seems to be fixed in the master branch. And the actual conflict wasn't in the coherence but the gettext change.

Anyway since the bug has fixed, I think we don't need to discuss more on this. This thread will be closed in a week.
