### ISSUE TITLE
Is Coherence ready to use with Phoenix 1.4.0-rc0?

### ISSUE THREAD

**Issue by dimitarvp** [smpallen99/coherence#386]
As per the title, do we have to do something extra if we want to use Coherence with Phoenix 1.4.0-rc0?

Also, is it a good idea to override Coherence's dependency on Phoenix? ("~> 1.3" at the moment)

To clarify, I use Phoenix like so right now:

```
      {:phoenix, "~> 1.4.0-rc", override: true},
```

**Comment by smpallen99** [comment]
I'm testing coherence master with phoenix-1.4.0-rc.0 right now on a newly generated project. The only thing I have had to do so far is add `override: true` to the `:phoenix` dependency in `mix.exs`. 

I'm not yet sure why @atavistock had an issue with `lib/yourapp_web/coherence_web.ex` router helpers. It already does a an `import YourappWeb.Router.Helpers`. The generated templates are working fine for me. 

I've also tested YourappWeb.Coherence.ViewHelpers.coherence_links(@conn, :layout) in my layout and that's working fine too. I'll give another update after generating the controllers and trying a few more install options.

**Comment by smpallen99** [comment]
I've tested registration, reset password, confirmation, unlock with token, trackable table, and generated controllers on a new coh install on a phx 1.4 project. 

Again, the only thing needed is to override the Phoenix dependency in your project. From what I understand, this is because of the `-rc` tag. Once Phoenix goes full 1.4, we should be good to go. 

BTW, I'm using Elixir 1.7.3. Coherence is compiling clean and all the project's generated files are compiling clean. 

So, I'd say that there are no issue with Coherence and Phoenix 1.4 and Elixir 1.7.3.

**Comment by atavistock** [comment]
Circling back.  When I create a completely clean install of Phoenix 1.4, add Coherence, and minimal setup (e.g. db credentials, coherence routes, etc), then I do not need to do anything with the route helpers.  So this does look good as is, not sure why I needed to make that change on my existing project.
